export const DISABLED_TABS_WHEN_NO_METADATA: string[] = [
  'indexing',
  'deduplication',
  'content',
  'deposit-compliance',
  'sdg',
  'das',
  'doi',
  'rights-retention-strategy',
  'research-software',
  'orcid',
  'usrn',
  'settings',
  // Settings children - redirect when settings is disabled
  'organisational',
  'repository',
  'notifications',
];

export const menuItems = [
  {
    test: /\/overview/,
    path: 'overview',
    icon: 'view-dashboard',
    label: 'Overview',
  },
  {
    test: /\/indexing/,
    path: 'indexing',
    icon: 'sync',
    label: 'Indexing status',
  },
  {
    test: /\/content/,
    path: 'content',
    icon: 'file-document',
    label: 'Content',
  },
  {
    test: /\/oa-compliance/,
    path: 'oa-compliance',
    icon: 'calendar-check',
    label: 'OA compliance',
    children: [
      {
        test: /\/deposit-compliance/,
        path: 'deposit-compliance',
        id: 'deposit-compliance',
        value: 'REF 2029',
        label: 'REF 2029',
      },
      {
        test: /\/validator/,
        path: 'validator',
        id: 'validator',
        value: 'Metadata validator',
        label: 'Metadata validator',
      },
      {
        test: /\/usrn/,
        path: 'usrn',
        id: 'usrn',
        value: 'Desirable Characteristics',
        label: 'Desirable Characteristics',
      },
    ],
  },
  {
    test: /\/enrichments/,
    path: 'enrichments',
    icon: 'enrichment',
    label: 'Enrichments',
    children: [
      {
        test: /\/doi/,
        path: 'doi',
        id: 'doi',
        value: 'DOI',
        label: 'DOI',
      },
      {
        test: /\/orcid/,
        path: 'orcid',
        id: 'orcid',
        value: 'ORCID',
        label: 'ORCID',
      },
      {
        test: /\/sdg/,
        path: 'sdg',
        id: 'sdg',
        value: 'SDG Insights',
        label: 'SDG Insights',
      },
      {
        test: /\/rights-retention-strategy/,
        path: 'rights-retention-strategy',
        id: 'rights-retention-strategy',
        value: 'RRS Policy',
        label: 'RRS Policy',
      },
      {
        test: /\/das/,
        path: 'das',
        id: 'das',
        value: 'DAS identification',
        label: 'DAS identification',
      },
      {
        test: /\/research-software/,
        path: 'research-software',
        id: 'research-software',
        value: 'Research software',
        label: 'Research software',
      },
      {
        test: /\/deduplication/,
        path: 'deduplication',
        id: 'deduplication',
        value: 'Versions/duplicates',
        label: 'Versions/duplicates',
      },
    ],
  },
  {
    test: /\/fair-certification/,
    path: 'fair-certification',
    icon: 'fair',
    label: 'FAIR Certification',
  },
  {
    test: /\/plugins/,
    path: 'plugins',
    icon: 'puzzle',
    label: 'Plugins',
  },
  {
    test: /\/membership/,
    path: 'membership',
    icon: 'account-group',
    label: 'Membership',
    children: [
      {
        test: /\/discovery/,
        path: 'membership-type',
        id: 'membership-type',
        value: 'My membership',
        label: 'My membership',
      },
      {
        test: /\/recommender/,
        path: 'documentation',
        id: 'documentation',
        value: 'Documentation',
        label: 'Documentation',
      },
      {
        test: /\/badges/,
        path: 'badges',
        id: 'badges',
        value: 'CORE badges',
        label: 'CORE badges',
      },
    ],
  },
  {
    test: /\/settings/,
    path: 'settings',
    icon: 'cog',
    label: 'Settings',
    children: [
      {
        test: /\/discovery/,
        path: 'organisational',
        id: 'organisational',
        value: 'Organisational',
        label: 'Organisational',
      },
      {
        test: /\/recommender/,
        path: 'repository',
        id: 'repository',
        value: 'Repository',
        label: 'Repository',
      },
      {
        test: /\/notifications/,
        path: 'notifications',
        id: 'notifications',
        value: 'Notifications',
        label: 'Notifications',
      },
    ],
  },
]

