title: Organisational settings

organisation:
  title: Your organisation
  rordescription: A ROR id is an identifier for the organisation connected with the repository. To search for ROR ids you can head to [https://ror.org/](https://ror.org)

invite:
  title: Invite colleagues to the repository dashboard
  buttonCaption: Invite
  listAccess: Colleagues that have access to the Dashboard
  confirmation:
    title: Confirmation
    content: |
      Access to the dashboard will be removed to user <span>{{email}}</span>. Do you want to proceed?

repository:
  title: Your repository

sets:
  title: Repository Sets
  description: Sets are an OAI-PMH solution that you can use to categorise your content. By adding sets in this section you enable the dashboard to show you both the global data and a view focussed only on a specific set.
mapping:
  title: Register OAI mapping
  description: This allows you to register a mapping between the OAI Prefix and the URL in your repository to which it should resolve. Once resolved and activated your OAI resolver will start resolving your OAIs directly to your repository metadata page. Where not registered, we will resolve to the metadata page in CORE. To find out more see [OAI identifier documentation](https://core.ac.uk/documentation/oai-resolver).
  form:
    - title: "The first part of your repository’s OAI identifiers until the colon:"
      label: OAI Prefix
      name: oaiPrefix
      helper: "Example:oai:digital.lib.washington.edu"
      disabled: true
    - title: "Mapping to your repository’s metadata page."
      label: URL Mapping
      name: urlMapping
      helper: "Example: digital.lib.washington.edu"
  switch:
    disabled: Activate resolving to your repository
    active: Resolving to your repository is activated
  buttonCaption: save

upload:
  title: Upload logo
  description: |
    You can now upload your official logo to make it easier for users to identify your content. The logo will be displayed next to your content in searches, in the CORE reader and on your data provider’s page.

    **Note**: This option available only for Supporting and Sustaining members
  imageCaption: 100х100, png, jpg.
  buttonCaptions:
    save: Save
    delete: Delete
    upload: upload
    change: Change
  deleteCaption: Are you sure you want to remove the logo?
  memberNote:
    title: Become a Supporting Member to get your logos promoted in CORE Search and across the CORE ecosystem.
    action:
      caption: Become a Supporting Member
      url: 'https://core.ac.uk/membership'

notifications:
  title: Email notifications
  subAction: Turn off all notification
  subActionDisabled: All notifications turned off
  subTitle: |
    Email me about updates on the following topics:
  messages:
    success: Harvesting has been successfully completed.
    issue: Harvesting was not completed because of issues that required your actions.
    duplicate: New potential duplicates of your records has been found.
  actions:
    show:
     name: Show all
     second: Hide
     action: ERROR
     variant: text
    read:
     name: mark all as read
     action: All
     variant: outlined
  noNotifications:
    title: You have no new notifications.
    description: Here you will see TABS.validation about events in your repository.
    action:
      title: OK
      variant: outlined
  types:
    harvesting:
      type: Indexing
      notifyOne: Notify me of the indexing status for my repository.
      notifyTwo: Send me a Harvesting Report email.
      radio:
        - title: Every month
          key: every month
        - title: Every 3 months
          key: 3 month
        - title: Every 6 months
          key: 6 month
        - title: Every time when indexing finished
          key: every time
    deduplication:
      type: Deduplication
      notifyOne: Notify me of duplicate records found in my repository.
      notifyTwo: Send me a Deduplication Report.
      radio:
        - title: Every month
          key: every month
        - title: Every 3 months
          key: 3 month
        - title: Every 6 months
          key: 6 month
        - title: Every time when deduplication finished
          key: every time

notificationGuide:
  title: Enable notifications for your repository
  description: |
    To ensure you're always informed about the latest updates concerning your repository, we'll send you email notifications. You have the freedom to customise the type and frequency of notifications in your settings.

    We promise that by enabling the notifications in the dashboard we won’t spam you with non-informative content but we will provide you email notifications on events happening in your repository life with CORE.
  actions:
    offAction:
      title: Disable notification
      type: text
    onAction:
      title: Enable notification
      type: contained

accessUsers:
  title: API access
  subTitle: Use case in which CORE data use
accessDataUsers :
  title: Dataset access
  subTitle: Use case in which CORE data use

license:
  title: Licencing
  description: |
    CORE recommends using machine-readable licence URLs in the respective metadata fields, depending on the metadata schema employed by your repository, to identify the licence of the content. Where the licence information is exposed, CORE complies with the conditions of the licence. More information about how to expose licencing is available in our documentation.

    One of the requirements for including a data provider in CORE is that the data provider exposes content in line with the principles of the BOAI2002.  If your repository contains mixed content, you have the option to request that CORE only indexes content which does not have an explicit licence.
  dropdown: Content without an explicit licence statement
  options:
    - value: Indexed and hosted (recommended)
      type: 0
      description: |
        CORE will index both metadata and full text content in your repository. CORE will be able to:
        * Increase the discoverability of your content in CORE Search, [Discovery]() and [Recommender]() and promote links to your content to our open scholarly infrastructure partners, such as PubMed Central via the [LinkOut]() cooperation, providing maximum visibility for your content on the Web and resulting in more exposure for your researchers.
        * Process your content to check for near-duplicates in your and other repositories.
        * Provide full support for the machine readability of your content in the CORE API and Dataset.
    - value:  Indexed only
      type: 1
      description: |
        CORE will index metadata and full text, but some functionalities will be affected.

  modal:
    title: |
      Changing to an “indexed only” option will have the following consequences:
    description: |
      * CORE Search ranks articles that are full Open Access (in accordance with BOAI) first

      * CORE Recommender only recommends to users full Open Access articles

      * CORE duplicate checker will be less accurate

      * The CORE Discovery will not recommend this content

      * The ability of CORE to enable machine readability of your content will be affected. Machine readability of research manuscripts might be mandated by the government or a funder in your country. Note that some countries operate text and data mining exceptions for research purposes, so only non-research use will be affected.
    actions:
      - title: save
      - title: cancel
