title: Settings

organisation:
  title: Organisation settings

invite:
  title: Invite
  buttonCaption: Invite

repository:
  title: Repository settings

mapping:
  title: Register OAI mapping
  description: |
      This allows you
      to register a mapping between the OAI Prefix and
      the URL in your repository to which it should resolve.
      Once resolved and activated your OAI resolver
      will start resolving your OAIs direct to your
      repository metadata page. Where not registered, we will
      resolve to the metadata page in CORE.
  form:
    - title: "The first part of your repository’s OAI identificators until the colon:"
      label: OAI Prefix
      name: oaiPrefix
      helper: "Example:oai:digital.lib.washington.edu"
      disabled: true
    - title: "Mapping to your repositorie’s metadata page."
      label: URL Mapping
      name: urlMapping
      helper: "Example: digital.lib.washington.edu"
  switch:
    disabled: Activate resolving to your repository
    active: Resolving to your repository is activated
  buttonCaption: save

upload:
  title: Upload logo
  description: |
        You can now upload your official logo to make it easier for users to identify your content.
        The logo will be displayed next to your content in searches, in the CORE reader and on your data provider’s page.
  imageCaption: 100х100, png, jpg.
  buttonCaptions:
    save: Save
    delete: Delete
    upload: upload
    change: Change
  deleteCaption: You sure about that?

