title: Settings

organisation:
  title: Your organisation

invite:
  title: Invite colleagues to the repository dashboard
  buttonCaption: Invite
  listAccess: Colleagues that have access to the Dashboard
  confirmation:
    title: Confirmation
    content: |
      Access to the dashboard will be removed to user <span>{{email}}</span>. Do you want to proceed?

repository:
  title: Repository settings

mapping:
  title: Register OAI mapping
  description: This allows you to register a mapping between the OAI Prefix and the URL in your repository to which it should resolve. Once resolved and activated your OAI resolver will start resolving your OAIs directly to your repository metadata page. Where not registered, we will resolve to the metadata page in CORE. To find out more see [OAI identifier documentation](https://core.ac.uk/documentation/oai-resolver).
  form:
    - title: "The first part of your repository’s OAI identifiers until the colon:"
      label: OAI Prefix
      name: oaiPrefix
      helper: "Example:oai:digital.lib.washington.edu"
      disabled: true
    - title: "Mapping to your repository’s metadata page."
      label: URL Mapping
      name: urlMapping
      helper: "Example: digital.lib.washington.edu"
  switch:
    disabled: Activate resolving to your repository
    active: Resolving to your repository is activated
  buttonCaption: save

upload:
  title: Upload logo
  description: |
        You can now upload your official logo to make it easier for users to identify your content.
        The logo will be displayed next to your content in searches, in the CORE reader and on your data provider’s page.
  imageCaption: 100х100, png, jpg.
  buttonCaptions:
    save: Save
    delete: Delete
    upload: upload
    change: Change
  deleteCaption: Are you sure you want to remove the logo?
  memberNote:
    title: "Become a Supporting Member to get your logos promoted in CORE Search and across the CORE ecosystem."
    action:
      caption: Join CORE Membership
      url: 'https://core.ac.uk/membership'

notifications:
  title: Email notifications
  subAction: Turn off all notification
  messages:
    success: Harvesting has been successfully completed.
    issue: Harvesting was not completed because of issues that required your actions.
    duplicate: New potential duplicates of your records has been found.
  actions:
    - name: mark as read
      action: All
      variant: outlined
    - name: Show all
      action: ERROR
      variant: text
  types:
    type: Harvesting
    notifyOne: Notify me whenever harvesting has completed.
    notifyTwo: Send me a Harvesting Report.
    items:
      month: Every month
      quarter: Every 3 months
      half: Every 6 months
#  - type: Deduplication
#    notify: Notify me whenever a new deduplication has completed.
#    notifyTwo: Send me a Deduplication Report.
#    items:
#      month: Every month
#      quarter: Every 3 months
#      half: Every 6 months

