name: Pull request check

on: [push]

env:
   NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   API_KEY: ${{ secrets.CORE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
# Deprecated version 12.x
# https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm ci --legacy-peer-deps
          npm run build
          npm run lint


