name: Pull request check

on: [push]

env:
   NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   API_KEY: ${{ secrets.CORE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
      - uses: actions/setup-node@v3
        with:
#          node-version: '12.x'
          node-version: '14'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
          npm run lint


